export const LOGINSUCESS = 'LOGINSUCESS'
export const LOGINFAILED = 'LOGINFAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const SET_SCREEN_WIDTH = 'SET_SCREEN_WIDTH';