export const LOGINSUCESS = 'LOGINSUCESS';
export const LOGINFAILED = 'LOGINFAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const RESET_SUCCESS = 'RESET_SUCCESS';
